# .github/workflows/pages.yml
name: Deploy PHP‐rendered Static to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring

      # ──────────────── 여기를 추가 ────────────────
      - name: Disable DB connect in index.php
        # index.php 상단에 있는 DB include 문을 주석 처리
        run: |
          sed -i "s|include *['\"]db/dbconn.php['\"];|// &|" index.php
      # ──────────────────────────────────────────

      - name: Prepare public folder
        run: |
          rm -rf public
          mkdir public
          cp -R css js images 404.html public/

      - name: Render PHP to HTML
        run: php index.php > public/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
